experiments:
- experiment_name: 1ppf_motif_only
  enzyme_id: 1ppf
  regime: motif_only
  chain: E
  pdb_file: /hpc/group/naderilab/darian/Enz/data/pdb/1ppf_chainE.pdb
  motif_pdb: /hpc/group/naderilab/darian/Enz/data/motifs/1ppf_motif_only/motif.pdb
  catalytic_resnums: &id001
  - 57
  - 102
  - 195
  catalytic_resnames:
  - HIS
  - ASP
  - SER
  fixed_resnums: *id001
  n_fixed_residues: 3
  contig: '[36/E57-57/36/E102-102/36/E195-195/39]'
  target_length: 150
  n_designs: 20
  n_seq_per_design: 5
  cutoff_angstroms: null
- experiment_name: 1ppf_shell5
  enzyme_id: 1ppf
  regime: shell5
  chain: E
  pdb_file: /hpc/group/naderilab/darian/Enz/data/pdb/1ppf_chainE.pdb
  motif_pdb: /hpc/group/naderilab/darian/Enz/data/motifs/1ppf_shell5/motif.pdb
  catalytic_resnums:
  - 57
  - 102
  - 195
  catalytic_resnames:
  - HIS
  - ASP
  - SER
  fixed_resnums:
  - 42
  - 43
  - 44
  - 54
  - 55
  - 56
  - 57
  - 58
  - 59
  - 60
  - 94
  - 99
  - 100
  - 101
  - 102
  - 103
  - 104
  - 191
  - 193
  - 194
  - 195
  - 196
  - 197
  - 212
  - 213
  - 214
  - 229
  n_fixed_residues: 27
  contig: '[13/E42-44/13/E54-60/13/E94-94/13/E99-104/13/E191-191/13/E193-197/13/E212-214/13/E229-229/13]'
  target_length: 150
  n_designs: 20
  n_seq_per_design: 5
  cutoff_angstroms: 5.0
- experiment_name: 1ppf_shell8
  enzyme_id: 1ppf
  regime: shell8
  chain: E
  pdb_file: /hpc/group/naderilab/darian/Enz/data/pdb/1ppf_chainE.pdb
  motif_pdb: /hpc/group/naderilab/darian/Enz/data/motifs/1ppf_shell8/motif.pdb
  catalytic_resnums:
  - 57
  - 102
  - 195
  catalytic_resnames:
  - HIS
  - ASP
  - SER
  fixed_resnums:
  - 16
  - 30
  - 31
  - 33
  - 40
  - 41
  - 42
  - 43
  - 44
  - 45
  - 53
  - 54
  - 55
  - 56
  - 57
  - 58
  - 59
  - 60
  - 61
  - 62
  - 92
  - 93
  - 94
  - 95
  - 96
  - 98
  - 99
  - 100
  - 101
  - 102
  - 103
  - 104
  - 139
  - 140
  - 141
  - 142
  - 177
  - 179
  - 180
  - 190
  - 191
  - 192
  - 193
  - 194
  - 195
  - 196
  - 197
  - 198
  - 211
  - 212
  - 213
  - 214
  - 215
  - 216
  - 227
  - 228
  - 229
  - 230
  - 231
  - 234
  - 237
  n_fixed_residues: 61
  contig: '[5/E16-16/5/E30-31/5/E33-33/5/E40-45/5/E53-62/5/E92-96/5/E98-104/5/E139-142/5/E177-177/5/E179-180/5/E190-198/5/E211-216/5/E227-231/5/E234-234/5/E237-237/5]'
  target_length: 150
  n_designs: 20
  n_seq_per_design: 5
  cutoff_angstroms: 8.0
- experiment_name: 1ca2_motif_only
  enzyme_id: 1ca2
  regime: motif_only
  chain: A
  pdb_file: /hpc/group/naderilab/darian/Enz/data/pdb/1ca2_chainA.pdb
  motif_pdb: /hpc/group/naderilab/darian/Enz/data/motifs/1ca2_motif_only/motif.pdb
  catalytic_resnums: &id002
  - 94
  - 96
  - 119
  catalytic_resnames:
  - HIS
  - HIS
  - HIS
  fixed_resnums: *id002
  n_fixed_residues: 3
  contig: '[36/A94-94/36/A96-96/36/A119-119/39]'
  target_length: 150
  n_designs: 20
  n_seq_per_design: 5
  cutoff_angstroms: null
- experiment_name: 1ca2_shell5
  enzyme_id: 1ca2
  regime: shell5
  chain: A
  pdb_file: /hpc/group/naderilab/darian/Enz/data/pdb/1ca2_chainA.pdb
  motif_pdb: /hpc/group/naderilab/darian/Enz/data/motifs/1ca2_shell5/motif.pdb
  catalytic_resnums:
  - 94
  - 96
  - 119
  catalytic_resnames:
  - HIS
  - HIS
  - HIS
  fixed_resnums:
  - 7
  - 65
  - 66
  - 67
  - 92
  - 93
  - 94
  - 95
  - 96
  - 97
  - 98
  - 104
  - 105
  - 106
  - 107
  - 115
  - 116
  - 117
  - 118
  - 119
  - 120
  - 121
  - 143
  - 144
  - 145
  - 199
  - 200
  - 209
  - 244
  - 245
  n_fixed_residues: 30
  contig: '[12/A7-7/12/A65-67/12/A92-98/12/A104-107/12/A115-121/12/A143-145/12/A199-200/12/A209-209/12/A244-245/12]'
  target_length: 150
  n_designs: 20
  n_seq_per_design: 5
  cutoff_angstroms: 5.0
- experiment_name: 1ca2_shell8
  enzyme_id: 1ca2
  regime: shell8
  chain: A
  pdb_file: /hpc/group/naderilab/darian/Enz/data/pdb/1ca2_chainA.pdb
  motif_pdb: /hpc/group/naderilab/darian/Enz/data/motifs/1ca2_shell8/motif.pdb
  catalytic_resnums:
  - 94
  - 96
  - 119
  catalytic_resnames:
  - HIS
  - HIS
  - HIS
  fixed_resnums:
  - 5
  - 7
  - 16
  - 29
  - 30
  - 51
  - 60
  - 62
  - 64
  - 65
  - 66
  - 67
  - 68
  - 69
  - 70
  - 90
  - 92
  - 93
  - 94
  - 95
  - 96
  - 97
  - 98
  - 103
  - 104
  - 105
  - 106
  - 107
  - 114
  - 115
  - 116
  - 117
  - 118
  - 119
  - 120
  - 121
  - 122
  - 142
  - 143
  - 144
  - 145
  - 146
  - 147
  - 148
  - 184
  - 194
  - 197
  - 198
  - 199
  - 200
  - 209
  - 210
  - 211
  - 223
  - 226
  - 241
  - 242
  - 243
  - 244
  - 245
  - 246
  n_fixed_residues: 61
  contig: '[5/A5-5/5/A7-7/5/A16-16/5/A29-30/5/A51-51/5/A60-60/5/A62-62/5/A64-70/5/A90-90/5/A92-98/5/A103-107/5/A114-122/5/A142-148/5/A184-184/5/A194-194/5/A197-200/5/A209-211/5/A223-223/5/A226-226/5/A241-246/5]'
  target_length: 150
  n_designs: 20
  n_seq_per_design: 5
  cutoff_angstroms: 8.0
